name:  Migrate Secrets
run-name: Migrate Secrets


on:
    workflow_dispatch:
      inputs:
        source-project:
          description: 'Select Source Project'
          required: true
          default: 'tst-aaa-blk-dev-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'

        target-project:
          description: 'Select Target Project'
          required: true
          default: 'tst-aaa-blk-qa-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'

        strato_env:
            description: 'Select Strato env of Source and Target projects'
            required: true
            default: 'staging'
            type: choice
            options: 
                - 'staging'
                - 'live'
        
jobs:
  convert_project_names:
    name: Get SA Secrets for the projects
    runs-on: ubuntu-latest
    outputs:
        SOURCE_PROJECT_INPUT: ${{ steps.get_project_names.outputs.SOURCE_PROJECT_INPUT }}
        TARGET_PROJECT_INPUT: ${{ steps.get_project_names.outputs.TARGET_PROJECT_INPUT }}
        SOURCE_SECRET_NAME: ${{ steps.get_project_names.outputs.SOURCE_SECRET_NAME }}
        TARGET_SECRET_NAME: ${{ steps.get_project_names.outputs.TARGET_SECRET_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          
      - name: Get Project names and modify them
        id: get_project_names
        run: |
            SOURCE_PROJECT_INPUT=${{ github.event.inputs.source-project }}
            TARGET_PROJECT_INPUT=${{github.event.inputs.target-project }}
            
            SOURCE_PROJECT=$(echo "$SOURCE_PROJECT_INPUT" | tr 'a-z' 'A-Z' | tr '-' '_') 
            TARGET_PROJECT=$(echo "$TARGET_PROJECT_INPUT" | tr 'a-z' 'A-Z' | tr '-' '_')
            SOURCE_SECRET_NAME=${SOURCE_PROJECT}_SA_SECRET
            TARGET_SECRET_NAME=${TARGET_PROJECT}_SA_SECRET
            echo $SOURCE_PROJECT_INPUT, $SOURCE_SECRET_NAME, $TARGET_PROJECT_INPUT, $TARGET_SECRET_NAME
            echo "::set-output name=SOURCE_PROJECT_INPUT::$SOURCE_PROJECT_INPUT"
            echo "::set-output name=TARGET_PROJECT_INPUT::$TARGET_PROJECT_INPUT"
            echo "::set-output name=SOURCE_SECRET_NAME::$SOURCE_SECRET_NAME"
            echo "::set-output name=TARGET_SECRET_NAME::$TARGET_SECRET_NAME"
    
  access-secrets:  
    name: Run Python Script
    runs-on: ubuntu-latest
    needs: convert_project_names
    environment: ${{ github.event.inputs.source-project }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up environment variables for secrets
          id: set_env
          run: |
            echo "SOURCE_PROJECT_INPUT=${{ needs.convert_project_names.outputs.SOURCE_PROJECT_INPUT }}" >> $GITHUB_ENV
            echo "TARGET_PROJECT_INPUT=${{ needs.convert_project_names.outputs.TARGET_PROJECT_INPUT }}" >> $GITHUB_ENV
            echo "SOURCE_SECRET_NAME=${{ needs.convert_project_names.outputs.SOURCE_SECRET_NAME }}" >> $GITHUB_ENV
            echo "TARGET_SECRET_NAME=${{ needs.convert_project_names.outputs.TARGET_SECRET_NAME }}" >> $GITHUB_ENV
        
        - name: Retrieve and use Secret Key
          run: |
            # Access the secrets using environment variables
            SOURCE_PROJECT=${{env.SOURCE_PROJECT_INPUT}}
            TARGET_PROJECT=${{env.TARGET_PROJECT_INPUT}}
            SOURCE_SECRET=${{ secrets[env.SOURCE_SECRET_NAME] }}
            TARGET_SECRET=${{ secrets[env.TARGET_SECRET_NAME] }}
            echo $SOURCE_PROJECT $SOURCE_SECRET $TARGET_PROJECT $TARGET_SECRET
            python -u main.py $SOURCE_PROJECT $SOURCE_SECRET $TARGET_PROJECT $TARGET_SECRET
