name:  Migrate Secrets
run-name: Migrate Secrets


on:
    workflow_dispatch:
      inputs:
        source-project:
          description: 'Select Source Project'
          required: true
          default: 'tst-aaa-blk-dev-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'


        target-project:
          description: 'Select Target Project'
          required: true
          default: 'tst-aaa-blk-qa-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'
        
jobs:
  convert_project_names:
    name: Get SA Secrets for the projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements
      - name: Get Project names and modify them
        run: |
            SOURCE_PROJECT=$(echo "${{ github.event.inputs.source-project }}" | tr 'a-z' 'A-Z' | tr '-' '_') 
            TARGET_PROJECT=$(echo "${{ github.event.inputs.target-project }}" | tr 'a-z' 'A-Z' | tr '-' '_')
            echo "SOURCE_PROJECT=$SOURCE_PROJECT" >> $GITHUB_ENV
            echo "TARGET_PROJECT=$TARGET_PROJECT" >> $GITHUB_ENV
    outputs:
        SOURCE_SECRET_NAME: ${{ join(env.SOURCE_PROJECT, '_SA_SECRET') }}
        TARGET_SECRET_NAME: ${{ join(env.TARGET_PROJECT, '_SA_SECRET') }}
  access-secrets:  
    name: Run Python Script
    runs-on: ubuntu-latest
    environment: staging
    steps:
        - name: Get Secret
          run: |
            SOURCE_SECRET_KEY=${{ needs.convert_project_names.outputs.SOURCE_SECRET_NAME }}
            TARGET_SECRET_KEY=${{ needs.convert_project_names.outputs.TARGET_SECRET_NAME }}
            echo $SOURCE_SECRET_KEY $TARGET_SECRET_KEY
            python -u main.py ${{env.SOURCE_PROJECT}} ${{env.SOURCE_SECRET}} ${{env.TARGET_PROJECT}} ${{env.TARGET_SECRET}}
