name:  Migrate Secrets
run-name: Migrate Secrets


on:
    workflow_dispatch:
      inputs:
        source-project:
          description: 'Select Source Project'
          required: true
          default: 'tst-aaa-blk-dev-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'


        target-project:
          description: 'Select Target Project'
          required: true
          default: 'tst-aaa-blk-qa-ini2-01'
          type: choice
          options:
            - 'tst-aaa-blk-dev-ini2-01'
            - 'tst-aaa-blk-qa-ini2-01'
        
jobs:
  convert_project_names:
    name: Get SA Secrets for the projects
    runs-on: ubuntu-latest
    outputs:
        SOURCE_SECRET_NAME: ${{ steps.get_project_names.outputs.SOURCE_PROJECT }}
        TARGET_SECRET_NAME: ${{ steps.get_project_names.outputs.SOURCE_PROJECT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements
      - name: Get Project names and modify them
        id: get_project_names
        run: |
            SOURCE_PROJECT=$(echo "${{ github.event.inputs.source-project }}" | tr 'a-z' 'A-Z' | tr '-' '_') 
            TARGET_PROJECT=$(echo "${{ github.event.inputs.target-project }}" | tr 'a-z' 'A-Z' | tr '-' '_')
            echo "::set-output name=SOURCE_PROJECT::$SOURCE_PROJECT"
            echo "::set-output name=TARGET_PROJECT::$TARGET_PROJECT"
    
  access-secrets:  
    name: Run Python Script
    runs-on: ubuntu-latest
    needs: convert_project_names
    environment: staging
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Get Secret
          run: |
            echo "${{ needs.convert_project_names.outputs.SOURCE_SECRET_NAME }}"
            SOURCE_SECRET_KEY="${{ needs.convert_project_names.outputs.SOURCE_SECRET_NAME }}_SA_SECRET"
            TARGET_SECRET_KEY="${{ needs.convert_project_names.outputs.TARGET_SECRET_NAME }}_SA_SECRET"
            echo "{{secrets.SOURCE_SECRET_KEY}}"
            echo "{{secrets.TARGET_SECRET_KEY}}"
            python -u main.py ${{env.SOURCE_PROJECT}} ${{env.SOURCE_SECRET}} ${{env.TARGET_PROJECT}} ${{env.TARGET_SECRET}}
